### PR TITLE
Updating Kubernetes quickstart

### PR DESCRIPTION
**Pull request by mheese**
This will update the Kubernetes quickstart with the following changes:
- fix instructions for operator changes
- add the fallback enforcer creation here
- add the creation of an optional automation which will install default fallback policies in every namespace that gets created

### CODE REVIEW

**Comment by mheese** [comment]
@dstiliadis this is for the changes as we discussed yesterday
@t00f including you here, so that we can update the backend once this is done
@emanic including you here, because we need to update the docs as well I guess... the quickstart should be the preferred way on how folks are getting started with a Kubernetes installation

it's still pending my local testing of everything for now ... sandbox is currently broken, so I'll continue with this later today

**Comment by emanic** [comment]
I see the UI quickstart as an alternative, not a replacement for the doc quickstart.

**Comment by mheese** [comment]
@emanic the changes are in the PR here (look at the success message, we adjusted those in the docs for 3.10 already).

IMHO, it's up to you if you want to keep both ways, however, keep in mind that this is making the "quickstart" in our docs more and more complex and lengthy. I'm fine with that if you think that it is maintainable. That said, I think we should point out that using the guided quickstart should be the preferred way for folks to create a new cluster. It reduces the amount of mistakes during the installation process that one can make.

**Comment by t00f** [comment]
@mheese,
For now, change look good... Is it fully functional on your side ? Should we test further ?

> @t00f including you here, so that we can update the backend once this is done
Can you please explain what is the update on the backend that is necessary ?

**Comment by mheese** [comment]
@t00f that's why it is still a draft :) ... was waiting on a working sandbox environment, so that I can test it

**Comment by mheese** [comment]
@t00f one last test run and this is ready for 3.11 ... please review already and tell me if you see something which is obviously wrong

@emanic can you check the "text" sections / documentation sections of the recipe please to see that this is inline with what we do in our docs?

**Pull request merged**
