### PR TITLE
Renamed 'Segment' to 'Microsegmentation'

### PR DESCRIPTION
**Pull request by ayliao**
PR for recipes to go along with the renaming in the UI https://github.com/aporeto-inc/clad/pull/1786

### CODE REVIEW

**Comment by ericrpowers** [comment]
Will need a new `signature` for recipes that were modified and require as much (eg `account-organizational-metadata.yaml`). I can do the required changes in https://github.com/aporeto-inc/voila/pull/114 once we get those. : )

**Comment by ayliao** [comment]
> Will need a new `signature` for recipes that were modified and require as much (eg `account-organizational-metadata.yaml`). I can do the required changes in [aporeto-inc/voila#114](https://github.com/aporeto-inc/voila/pull/114) once we get those. : )

Sorry, I don't think I'm following you @ericrpowers haha. Is there an additional action that I need to take here?

**Comment by ericrpowers** [comment]
Certain recipes have a field `signature` that matches to the file. When we change the contents, we need to regenerate a new signature. @t00f knows how to do this for us, so we will need that for the changes to not be denied when trying to deploy the recipe.

**Comment by ayliao** [comment]
> Certain recipes have a field `signature` that matches to the file. When we change the contents, we need to regenerate a new signature. @t00f knows how to do this for us, so we will need that for the changes to not be denied when trying to deploy the recipe.
> 
> For example, you changed the contents of `account-organizational-metadata.yaml` which will require a regeneration of a new signature now: https://github.com/aporeto-inc/cookbook/blob/master/account-organizational-metadata.yaml#L7

Ahh I see! Thank you for taking the time to explain :D

**Pull request merged**
